# Generated by Django 3.1.7 on 2021-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('hectare', models.CharField(max_length=3)),
                ('count', models.IntegerField()),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('above_ground', models.IntegerField()),
                ('shift', models.SmallIntegerField(choices=[(0, 'A M '), (1, 'P M ')])),
                ('age', models.SmallIntegerField(choices=[(0, 'Adult'), (1, 'Juvenile'), (2, 'Unknown')])),
            ],
        ),
    ]
