# Generated by Django 3.2 on 2021-04-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('hectare', models.CharField(max_length=3)),
                ('Hectare_count', models.IntegerField()),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('kuks', models.BooleanField()),
                ('quaas', models.BooleanField()),
                ('moans', models.BooleanField()),
                ('tail_flags', models.BooleanField()),
                ('tail_twitches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runs_from', models.BooleanField()),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=5)),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', 'Unknown')], max_length=10)),
                ('location', models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], max_length=15)),
                ('primary_fur_color', models.CharField(blank=True, max_length=10)),
                ('highlight_fur_color', models.CharField(blank=True, max_length=50)),
                ('combination_color', models.CharField(blank=True, max_length=50)),
                ('color_notes', models.TextField(blank=True)),
                ('above_ground_sighter_measurement', models.CharField(blank=True, max_length=10)),
                ('specific_location', models.CharField(blank=True, max_length=100)),
                ('other_activity', models.CharField(blank=True, max_length=100)),
                ('other_interaction', models.CharField(blank=True, max_length=200)),
                ('lat_long', models.CharField(max_length=50)),
            ],
        ),
    ]
