# Generated by Django 3.2 on 2021-04-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='id',
            new_name='squirrel_id',
        ),
    ]
