# Generated by Django 3.2 on 2021-04-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_id_sighting_squirrel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='Hectare_count',
            new_name='count',
        ),
    ]
