# Generated by Django 3.2 on 2021-04-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_hectare_count_sighting_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='above_ground_sighter_measurement',
        ),
        migrations.AddField(
            model_name='sighting',
            name='above_ground',
            field=models.IntegerField(default=0),
        ),
    ]
