# Generated by Django 3.2 on 2021-04-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_sighting_above_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
