# Generated by Django 3.2 on 2021-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_sighting_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='other_activity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='other_interaction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='specific_location',
            field=models.TextField(blank=True),
        ),
    ]
